### ISSUE TITLE
Better than Blocks?

### ISSUE THREAD

**Issue by mdangear** [CommonAccord/Site-Startup#9]
Jim,
You mentioned that you have a better way to do signature blocks than what I have been doing with my BB_Blocks.md. Can you tell me how you do this? or point me to an example of how you do it?

**Comment by jamesghazard** [comment]
Here's an example - http://www.commonaccord.org/index.php?action=source&file=doc/escrow/Demo_Escrow_Step_1_Parties  You will note that the individual has a different (appropriate) signature block than the two corporations.  This is done by making signature a part of the characteristics of the person - just like their address is.  You have to drill down on the person, down through the [U/class/ID..] elements to Sign.Block.   By fleshing out the description of the person, they come to have a signature block.

**Comment by jamesghazard** [comment]
Obviously, the key point here is how are identities managed.  Each person should have an identity and everyone should use those identities - having access to only a certain level of information.  The identity should tie to relevant info, including addresses for instance -   http://my.commonaccord.org/index.php?action=source&file=U/id/acme_incorporated

**Comment by mdangear** [comment]
So you include the Signature and Notification blocks in the in the Company ID. I can see that this can be a good option. Do you have an example of a file where you use this? I am curious about formatting once you get into having to put 2 signature blocks next to each other. Also what is {xSignature}?

**Comment by jamesghazard** [comment]
Here's an example of two Sign.Blocks next to one another.  The underlying component, part of /Z/Agt/Agt.md, will handle up to six blocks -  by parameterizing as Sign.List-2, Sign.List-3, etc. http://my.commonaccord.org/index.php?action=source&file=Z/Agt/Agt_End.md

**Comment by mdangear** [comment]
Very elegant indeed, I will implement this in our docs!

**Comment by HazardJ** [comment]
Traveling now, also did a French version at fr.commonaccord.org.

**Comment by mdangear** [comment]
Ok. So I am adding a Sign.Block and and Notif.Block in Champs.base actually, this seems to be the most logical for what I have. This way I will not need the BB_Blocks any more, simpler. Thanks for the tip.
